"""Stable imports for the native and retained paired wire protocol domains.

Policy lives in the named domain modules. Explicit reexports include historical
underscore helpers used by host integrations; the public wildcard list is kept
unchanged. No transport runtime is started by these contracts.
"""
from __future__ import annotations

# Preserve the historical imported names as well as the contract definitions.
import base64
import hashlib
import hmac
import json
import math
import re
import uuid
from dataclasses import dataclass
from datetime import datetime
from typing import Any

from .events import EVENT_TYPES
from .generative_ui import canonical_json, validate_rendered_envelope
from .groups_contracts import (
    GROUPS_RESULT_PAYLOAD_BYTES, GROUPS_RESULT_ENVELOPE_BYTES, GROUPS_RESULTS_CAPABILITY,
    validate_log_page, validate_result_version,
)
from .project_git_validation import ProjectGitValidation
from .wiki_contract import (
    WIKI_OPERATIONS, available_wiki_operations,
    bounded_result as bound_wiki_result, validate_payload as validate_wiki_payload,
)
from .workspace_operations import GROUP_HANDLERS, WORKSPACE_HANDLERS

from .protocol_values import (
    DIRECT_ENROLLMENT_CAPABILITY,
    DIRECTED_FRAMES_CAPABILITY,
    MAX_ATTACHMENT_BYTES,
    MAX_MESSAGE_ATTACHMENT_BYTES,
    MAX_ATTACHMENT_CHUNK_BYTES,
    MAX_ATTACHMENT_CHUNKS,
    MAX_AGENT_ATTACHMENT_BYTES,
    MAX_AGENT_ATTACHMENT_CHUNKS,
    PLUGIN_VERSION,
    _OPAQUE,
    _opaque,
    _session_coordinate,
    _label,
    _activity_label,
    _activity_detail,
    _picker_identifier,
    _text,
    _positive,
    _nonnegative,
    _decode_b64url,
    _b64url,
)
from .device_tool_contracts import (
    MAX_DEVICE_TOOL_PAYLOAD_BYTES,
    MAX_DEVICE_TOOL_ARGUMENT_BYTES,
    MAX_DEVICE_TOOL_DATE_RANGE_SECONDS,
    MAX_DEVICE_TOOL_LIST_LIMIT,
    MAX_DEVICE_TOOL_ID_COUNT,
    DEVICE_TOOL_CAPABILITY,
    DEVICE_TOOL_OPERATIONS,
    HEALTH_TYPES,
    device_tool_request,
    parse_device_tool_request,
    device_tool_result,
    parse_device_tool_result,
    device_tool_status,
    parse_device_tool_status,
    _device_tool_turn_id,
    _device_tool_operation,
    _device_tool_json,
    _device_tool_string,
    _device_tool_date,
    _device_tool_range,
    _device_tool_ordered_dates,
    _device_tool_limit,
    _device_tool_id_list,
    _device_tool_arguments,
    _json_size,
)
from .workspace_wire_contracts import (
    MAX_AVATAR_WORKSPACE_PLAINTEXT_BYTES,
    AVAILABLE_WIKI_OPERATIONS,
    GROUPS_OPERATIONS,
    LIVE_VOICE_OPERATIONS,
    WORKSPACE_OPERATIONS,
    WorkspaceRequest,
    parse_workspace_request,
    workspace_capabilities,
    workspace_rejection,
    workspace_result,
    _project_git_workspace_payload,
    _git_values,
    _project_git_input,
    _project_git_path,
    _project_git_ref_name,
    _project_git_choice,
    _project_git_status_token,
    _bounded_integer,
    _workspace_json,
    _workspace_json_allowing_dashboard_cards,
    _workspace_json_allowing_skill_archive,
    _workspace_json_allowing_avatar_blobs,
    _workspace_avatar_placeholder_value,
    _validate_workspace_avatar_blobs,
    _avatar_payload,
)
from .session_control_contracts import (
    PickerOpen,
    PickerSelection,
    SessionForkRequest,
    CommandCatalogRequest,
    PersonalityRequest,
    parse_personality_request,
    personality_catalog_payload,
    parse_picker_open,
    parse_picker_selection,
    parse_session_fork_request,
    parse_command_catalog_request,
    command_catalog_payload,
    verified_fork_prefix,
    session_fork_result,
    model_picker_payload,
    choice_picker_payload,
    picker_result,
    _picker_title,
    _picker_result_message,
    _model_picker_identifier,
    _command_name,
    _command_args_hint,
    _personality_name,
    _personality_definition,
    _personality_line,
)
from .voice_speak_contracts import (
    VoiceSpeakRequest,
    parse_voice_speak_request,
    voice_audio_chunks,
    voice_speak_error,
)
from .presentation_contracts import (
    STATE_BACKED_PRESENTATION_CAPABILITY,
    is_transient_presentation,
    GenerativeUIFormSubmission,
    parse_generative_ui_form_submission,
    assistant_message,
    notification_event,
    activity_event,
    session_context,
    session_todos,
    session_subagents,
    generative_ui_event,
    generative_ui_form_result,
    _form_submission_values,
)
from .link_transport_contracts import (
    parse_direct_enrollment,
    _MIME_TYPE,
    MAX_ENCRYPTED_FRAME_CHARACTERS,
    EncryptedFrame,
    AttachmentReference,
    AttachmentChunk,
    UserMessage,
    ExpiredHostRelayEnrollment,
    RelayReady,
    parse_encrypted_frame,
    parse_user_message,
    parse_attachment_chunk,
    _attachment_reference,
    parse_relay_ready,
    parse_backpressure,
)


__all__ = [
    "AttachmentChunk",
    "AttachmentReference",
    "CommandCatalogRequest",
    "EncryptedFrame",
    "GenerativeUIFormSubmission",
    "PickerOpen",
    "PickerSelection",
    "PersonalityRequest",
    "RelayReady",
    "SessionForkRequest",
    "UserMessage",
    "VoiceSpeakRequest",
    "WorkspaceRequest",
    "DEVICE_TOOL_CAPABILITY",
    "DIRECTED_FRAMES_CAPABILITY",
    "DEVICE_TOOL_OPERATIONS",
    "HEALTH_TYPES",
    "MAX_DEVICE_TOOL_PAYLOAD_BYTES",
    "MAX_DEVICE_TOOL_ARGUMENT_BYTES",
    "device_tool_request",
    "device_tool_result",
    "device_tool_status",
    "AVAILABLE_WIKI_OPERATIONS",
    "GROUPS_OPERATIONS",
    "WORKSPACE_OPERATIONS",
    "activity_event",
    "assistant_message",
    "choice_picker_payload",
    "command_catalog_payload",
    "generative_ui_event",
    "generative_ui_form_result",
    "model_picker_payload",
    "notification_event",
    "parse_encrypted_frame",
    "parse_generative_ui_form_submission",
    "parse_attachment_chunk",
    "parse_picker_open",
    "parse_picker_selection",
    "parse_personality_request",
    "parse_command_catalog_request",
    "parse_relay_ready",
    "parse_session_fork_request",
    "parse_user_message",
    "parse_voice_speak_request",
    "parse_workspace_request",
    "parse_device_tool_request",
    "parse_device_tool_result",
    "parse_device_tool_status",
    "picker_result",
    "personality_catalog_payload",
    "session_context",
    "session_subagents",
    "session_todos",
    "session_fork_result",
    "verified_fork_prefix",
    "voice_audio_chunks",
    "voice_speak_error",
    "workspace_result",
    "workspace_capabilities",
    "workspace_rejection",
    "parse_backpressure",
]
