"""Finite workspace backend operation registry, independent of transports.

Wiki availability is platform-gated separately. Live voice is adapter-owned and
intentionally absent from this backend registry.
"""

GROUP_HANDLERS = {
    'groups.approve': 'groups_approve',
    'groups.capabilities': 'groups_capabilities',
    'groups.create': 'groups_create',
    'groups.demote': 'groups_demote',
    'groups.disband': 'groups_disband',
    'groups.list': 'groups_list',
    'groups.log': 'groups_log',
    'groups.peer.invite': 'groups_peer_invite',
    'groups.peer.register': 'groups_peer_register',
    'groups.peer.revoke': 'groups_peer_revoke',
    'groups.promote': 'groups_promote',
    'groups.rename': 'groups_rename',
    'groups.replica_state': 'groups_replica_state',
    'groups.replicate': 'groups_replicate',
    'groups.retry': 'groups_retry',
    'groups.send': 'groups_send',
    'groups.state': 'groups_state',
    'groups.stop': 'groups_stop',
}

WORKSPACE_HANDLERS = {
    'agents.list': 'agents_list',
    'host_runtime.status': 'host_runtime_status',
    'plugin_update.start': 'plugin_update_start',
    'plugin_update.status': 'plugin_update_status',
    'agents.create': 'agents_create',
    'agents.update': 'agents_update',
    'agents.avatar.get': 'agents_avatar_get',
    'agents.avatar.set': 'agents_avatar_set',
    'sessions.list': 'sessions_list',
    'sessions.history': 'sessions_history',
    'sessions.state': 'sessions_state',
    'sessions.content': 'sessions_content',
    'sessions.update': 'sessions_update',
    'sessions.delete': 'sessions_delete',
    'attachments.resolve': 'attachments_resolve',
    'attachments.fetch': 'attachments_fetch',
    'generated_media.resolve': 'generated_media_resolve',
    'scheduled_tasks.list': 'scheduled_tasks_list',
    'scheduled_tasks.delivery_targets': 'scheduled_tasks_delivery_targets',
    'scheduled_tasks.create': 'scheduled_tasks_create',
    'scheduled_tasks.update': 'scheduled_tasks_update',
    'scheduled_tasks.delete': 'scheduled_tasks_delete',
    'scheduled_tasks.pause': 'scheduled_tasks_pause',
    'scheduled_tasks.resume': 'scheduled_tasks_resume',
    'scheduled_tasks.run': 'scheduled_tasks_run',
    'agent_defaults.get': 'agent_defaults_get',
    'agent_defaults.set': 'agent_defaults_set',
    'voice_settings.get': 'voice_settings_get',
    'voice_settings.set': 'voice_settings_set',
    'skills_tools.list': 'skills_tools_list',
    'skills_tools.get': 'skills_tools_get',
    'skills_tools.create': 'skills_tools_create',
    'skills_tools.update': 'skills_tools_update',
    'skills_tools.import': 'skills_tools_import',
    'cards.templates.list': 'cards_templates_list',
    'cards.templates.install': 'cards_templates_install',
    'cards.templates.remove': 'cards_templates_remove',
    'projects.list': 'projects_list',
    'projects.set_active': 'projects_set_active',
    'projects.create': 'projects_create',
    'projects.archive': 'projects_archive',
    'projects.list_directory': 'projects_list_directory',
    'projects.git.capabilities': 'projects_git_capabilities',
    'projects.git.status': 'projects_git_status',
    'projects.git.diff': 'projects_git_diff',
    'projects.git.prepare': 'projects_git_prepare',
    'projects.git.execute': 'projects_git_execute',
    'dashboard.load': 'dashboard_load',
    'dashboard.set_event_state': 'dashboard_set_event_state',
    'dashboard.dismiss_event': 'dashboard_dismiss_event',
    'dashboard.dismiss_events': 'dashboard_dismiss_events',
    'approvals.load': 'approvals_load',
    'approvals.respond': 'approvals_respond',
    'clarifications.respond': 'clarifications_respond',
    **GROUP_HANDLERS,
}
