//  AgentAvatarView.swift
//  bighelp agent avatars for SwiftUI. Generated by tools/build.py; regenerate rather than edit presets by hand.
//
//  Setup: add every file in /svg to your app target (Copy Bundle Resources).
//
//  AgentAvatarView(.lobster, colors: .neon, state: agent.isStreaming ? .talking : .idle)
//      .frame(width: 96, height: 96)
//
//  Bits (geometric bots) also take a face:
//  AgentAvatarView(.orb, face: .init(eyes: .visor, mouth: .fang, accessory: .headset), state: .waiting)
//
//  Tapping squishes the avatar and calls onPoke. The eyes follow touches over the avatar.

import SwiftUI
import WebKit

public enum AgentAvatarState: String, CaseIterable, Sendable {
    case idle, listening, thinking, waiting, talking, happy, sleeping
}

public enum AgentAvatarCharacter: String, CaseIterable, Sendable {
    case lobster
    case messenger
    case dog
    case cat
    case zeus
    case robot
    case owl
    case octopus
    case fox
    case dragon
    case orb
    case cube
    case wedge
    case hex
    case drop
    case capsule
    case cloud
    case ghost
    case bloom
    case gem

    public var displayName: String {
        switch self {
        case .lobster: return "Pinch"
        case .messenger: return "Aeria"
        case .dog: return "Biscuit"
        case .cat: return "Miso"
        case .zeus: return "Bolt"
        case .robot: return "Rivet"
        case .owl: return "Sage"
        case .octopus: return "Inky"
        case .fox: return "Kit"
        case .dragon: return "Ember"
        case .orb: return "Bop"
        case .cube: return "Blok"
        case .wedge: return "Wedge"
        case .hex: return "Hexo"
        case .drop: return "Drip"
        case .capsule: return "Tic"
        case .cloud: return "Puff"
        case .ghost: return "Boo"
        case .bloom: return "Bloom"
        case .gem: return "Glim"
        }
    }

    /// Bits are the geometric bots that accept an `AgentAvatarFace`.
    public var isBit: Bool {
        switch self {
        case .lobster: return false
        case .messenger: return false
        case .dog: return false
        case .cat: return false
        case .zeus: return false
        case .robot: return false
        case .owl: return false
        case .octopus: return false
        case .fox: return false
        case .dragon: return false
        case .orb: return true
        case .cube: return true
        case .wedge: return true
        case .hex: return true
        case .drop: return true
        case .capsule: return true
        case .cloud: return true
        case .ghost: return true
        case .bloom: return true
        case .gem: return true
        }
    }
}

public enum AgentAvatarEyes: String, CaseIterable, Codable, Sendable {
    case round
    case dot
    case pill
    case square
    case lidded
    case visor
    case cyclops
}

public enum AgentAvatarMouth: String, CaseIterable, Codable, Sendable {
    case smile
    case cat
    case flat
    case fang
    case hidden = "none"
}

public enum AgentAvatarAccessory: String, CaseIterable, Codable, Sendable {
    case bare = "none"
    case antenna
    case sprout
    case halo
    case crown
    case bow
    case headset
}

/// Face options for Bits. Nil values use that Bit's own defaults; classic characters ignore this.
public struct AgentAvatarFace: Equatable, Codable, Sendable {
    public var eyes: AgentAvatarEyes?
    public var mouth: AgentAvatarMouth?
    public var accessory: AgentAvatarAccessory?
    public var cheeks: Bool

    public init(eyes: AgentAvatarEyes? = nil, mouth: AgentAvatarMouth? = nil,
                accessory: AgentAvatarAccessory? = nil, cheeks: Bool = true) {
        self.eyes = eyes; self.mouth = mouth; self.accessory = accessory; self.cheeks = cheeks
    }

    public static let `default` = AgentAvatarFace()

    var json: String {
        guard let data = try? JSONEncoder().encode(self), let s = String(data: data, encoding: .utf8) else { return "{}" }
        return s
    }
}

/// A colorway. Any nil value falls back to the character's own palette.
public struct AgentAvatarColors: Equatable, Sendable, Codable {
    public var primary: String?
    public var secondary: String?
    public var accent: String?
    public var background: String?
    public var ink: String?
    public var skin: String?

    public init(primary: String? = nil, secondary: String? = nil, accent: String? = nil,
                background: String? = nil, ink: String? = nil, skin: String? = nil) {
        self.primary = primary; self.secondary = secondary; self.accent = accent
        self.background = background; self.ink = ink; self.skin = skin
    }

    /// Overlay per-agent overrides on top of a preset.
    public func merged(with other: AgentAvatarColors) -> AgentAvatarColors {
        AgentAvatarColors(primary: other.primary ?? primary, secondary: other.secondary ?? secondary,
                          accent: other.accent ?? accent, background: other.background ?? background,
                          ink: other.ink ?? ink, skin: other.skin ?? skin)
    }

    /// Each character keeps its own palette.
    public static let original = AgentAvatarColors()
    /// Midnight colorway.
    public static let midnight = AgentAvatarColors(primary: "#5A6CFF", secondary: "#AEB8FF", accent: "#FFD166", background: "#1C2045", ink: "#0F1130")
    /// Neon colorway.
    public static let neon = AgentAvatarColors(primary: "#FF3EA5", secondary: "#7CF7FF", accent: "#F9F871", background: "#1A0B2E", ink: "#13071F")
    /// Sunset colorway.
    public static let sunset = AgentAvatarColors(primary: "#FF7A45", secondary: "#FFC36B", accent: "#9B5DE5", background: "#FFE6D6", ink: "#3A1B2F")
    /// Forest colorway.
    public static let forest = AgentAvatarColors(primary: "#3E9B5E", secondary: "#BCE4AE", accent: "#F2C14E", background: "#E4F2E0", ink: "#1E3326")
    /// Ocean colorway.
    public static let ocean = AgentAvatarColors(primary: "#2383E2", secondary: "#A3D3FF", accent: "#FFB547", background: "#E2F1FF", ink: "#0F2A45")
    /// Royal colorway.
    public static let royal = AgentAvatarColors(primary: "#7B52D6", secondary: "#E3CCFF", accent: "#FFC53D", background: "#F2EAFF", ink: "#25123F")
    /// Bubblegum colorway.
    public static let bubblegum = AgentAvatarColors(primary: "#FF8AB3", secondary: "#FFDCE9", accent: "#5FCBFF", background: "#FFF0F6", ink: "#3D1F2E")
    /// Mono colorway.
    public static let mono = AgentAvatarColors(primary: "#7A7A86", secondary: "#D8D8DF", accent: "#FF5A5F", background: "#EFEFF3", ink: "#18181C")

    public static let presets: [(id: String, name: String, colors: AgentAvatarColors)] = [
        ("original", "Original", .original),
        ("midnight", "Midnight", .midnight),
        ("neon", "Neon", .neon),
        ("sunset", "Sunset", .sunset),
        ("forest", "Forest", .forest),
        ("ocean", "Ocean", .ocean),
        ("royal", "Royal", .royal),
        ("bubblegum", "Bubblegum", .bubblegum),
        ("mono", "Mono", .mono)
    ]

    var json: String {
        guard let data = try? JSONEncoder().encode(self), let s = String(data: data, encoding: .utf8) else { return "{}" }
        return s
    }
}

public struct AgentAvatarView: UIViewRepresentable {
    public var character: AgentAvatarCharacter
    public var colors: AgentAvatarColors
    public var face: AgentAvatarFace
    public var state: AgentAvatarState
    public var showsBackground: Bool
    public var tracksTouch: Bool
    public var onPoke: (() -> Void)?

    public init(_ character: AgentAvatarCharacter,
                colors: AgentAvatarColors = .original,
                face: AgentAvatarFace = .default,
                state: AgentAvatarState = .idle,
                showsBackground: Bool = true,
                tracksTouch: Bool = true,
                onPoke: (() -> Void)? = nil) {
        self.character = character
        self.colors = colors
        self.face = face
        self.state = state
        self.showsBackground = showsBackground
        self.tracksTouch = tracksTouch
        self.onPoke = onPoke
    }

    public func makeCoordinator() -> Coordinator { Coordinator() }

    public func makeUIView(context: Context) -> WKWebView {
        let controller = WKUserContentController()
        controller.add(WeakMessageHandler(context.coordinator), name: "bhPoke")
        let config = WKWebViewConfiguration()
        config.userContentController = controller
        config.suppressesIncrementalRendering = true

        let web = WKWebView(frame: .zero, configuration: config)
        web.isOpaque = false
        web.backgroundColor = .clear
        web.scrollView.backgroundColor = .clear
        web.scrollView.isScrollEnabled = false
        web.scrollView.bounces = false
        web.scrollView.contentInsetAdjustmentBehavior = .never
        web.navigationDelegate = context.coordinator
        web.isAccessibilityElement = true
        web.accessibilityLabel = character.displayName

        context.coordinator.parent = self
        context.coordinator.load(into: web)
        return web
    }

    public func updateUIView(_ web: WKWebView, context: Context) {
        context.coordinator.parent = self
        web.accessibilityLabel = character.displayName
        if context.coordinator.loaded != character {
            context.coordinator.load(into: web)
        } else {
            context.coordinator.sync(web)
        }
    }

    public static func dismantleUIView(_ web: WKWebView, coordinator: Coordinator) {
        web.configuration.userContentController.removeScriptMessageHandler(forName: "bhPoke")
    }

    @MainActor
    public final class Coordinator: NSObject, WKNavigationDelegate, WKScriptMessageHandler {
        var parent: AgentAvatarView?
        var loaded: AgentAvatarCharacter?
        private var ready = false

        func load(into web: WKWebView) {
            guard let p = parent else { return }
            loaded = p.character
            ready = false
            guard let url = Bundle.main.url(forResource: p.character.rawValue, withExtension: "svg"),
                  let svg = try? String(contentsOf: url, encoding: .utf8) else {
                assertionFailure("\(p.character.rawValue).svg is missing from the app bundle")
                return
            }
            web.loadHTMLString(Self.page(svg: svg, initialCall: call(for: p)), baseURL: nil)
        }

        func sync(_ web: WKWebView) {
            guard ready, let p = parent else { return }
            web.evaluateJavaScript(call(for: p), completionHandler: nil)
        }

        private func call(for p: AgentAvatarView) -> String {
            "window.bh&&bh.set('\(p.state.rawValue)',\(p.colors.json),\(p.showsBackground),\(p.tracksTouch),\(p.face.json));"
        }

        public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
            ready = true
            sync(webView)
        }

        public func userContentController(_ userContentController: WKUserContentController,
                                          didReceive message: WKScriptMessage) {
            parent?.onPoke?()
        }

        static func page(svg: String, initialCall: String) -> String {
            """
            <!doctype html><html><head>
            <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
            <style>html,body{margin:0;width:100%;height:100%;background:transparent;overflow:hidden;\
            -webkit-user-select:none;-webkit-touch-callout:none}svg{width:100%;height:100%;display:block}</style>
            </head><body>\(svg)<script>
            (function(){
              var svg=document.querySelector('svg'),track=true,
                  F={eyes:'data-eyes',mouth:'data-mouth',accessory:'data-acc'},D={},
                  V={primary:'--av-primary',secondary:'--av-secondary',accent:'--av-accent',background:'--av-bg',ink:'--av-ink',skin:'--av-skin'};
              for(var f in F)D[f]=svg.getAttribute(F[f]);
              function clamp(v){return Math.max(-1,Math.min(1,v)).toFixed(3)}
              function look(x,y){svg.style.setProperty('--lx',clamp(x));svg.style.setProperty('--ly',clamp(y))}
              function lookAt(e){var r=svg.getBoundingClientRect();look((e.clientX-r.left-r.width/2)/(r.width/2),(e.clientY-r.top-r.height*.45)/(r.height/2))}
              window.bh={set:function(state,colors,bg,t,face){
                svg.setAttribute('data-state',state);svg.setAttribute('data-bg',bg?'on':'off');
                if(D.eyes){face=face||{};for(var f in F)svg.setAttribute(F[f],face[f]||D[f]);
                  svg.setAttribute('data-cheeks',face.cheeks===false?'off':'on');}
                for(var k in V){colors[k]?svg.style.setProperty(V[k],colors[k]):svg.style.removeProperty(V[k])}
                track=t;if(!t)look(0,0);
              }};
              addEventListener('pointerdown',function(e){
                svg.classList.remove('bh-poke');void svg.getBoundingClientRect();svg.classList.add('bh-poke');
                if(track)lookAt(e);
                window.webkit&&webkit.messageHandlers.bhPoke&&webkit.messageHandlers.bhPoke.postMessage(1);
              });
              addEventListener('pointermove',function(e){if(track)lookAt(e)});
              addEventListener('pointerup',function(){setTimeout(function(){look(0,0)},700)});
              svg.addEventListener('animationend',function(e){if(e.animationName==='bh-squish')svg.classList.remove('bh-poke')});
              \(initialCall)
            })();
            </script></body></html>
            """
        }
    }
}

/// Avoids the retain cycle WKUserContentController creates with its handlers.
@MainActor
private final class WeakMessageHandler: NSObject, WKScriptMessageHandler {
    weak var target: WKScriptMessageHandler?
    init(_ target: WKScriptMessageHandler) { self.target = target }
    func userContentController(_ controller: WKUserContentController, didReceive message: WKScriptMessage) {
        target?.userContentController(controller, didReceive: message)
    }
}

#Preview {
    ScrollView {
        LazyVGrid(columns: [GridItem(.adaptive(minimum: 96))], spacing: 12) {
            ForEach(AgentAvatarCharacter.allCases, id: \.self) { c in
                AgentAvatarView(c, colors: .original, state: .idle).frame(width: 96, height: 96)
            }
            AgentAvatarView(.cube, colors: .neon, face: .init(eyes: .cyclops, accessory: .halo), state: .waiting)
                .frame(width: 96, height: 96)
        }.padding()
    }
}
